ARG FEDORA_VERSION=${FEDORA_VERSION:-39}
ARG VARIANT=${VARIANT:-desktop}

FROM ghcr.io/fossrob/fedora-custom:${FEDORA_VERSION}

ARG FEDORA_VERSION
ARG VARIANT

COPY --from=ghcr.io/ublue-os/config:latest files/ublue-os-just /

COPY packages.${VARIANT}.sh /tmp/

RUN echo "Customising packages..." && \
      /tmp/packages.${VARIANT}.sh && \
    echo "...done!"

RUN echo "Clean up and commit..." && \
      rm -rf /tmp/* /var/* && \
      ostree container commit && \
    echo "...done!"
