name: build-os

on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 1,7,13,19 * * *
  workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  gh_registry: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ fedora ]
        variant: [ desktop, laptop, z ]
        version: [ 39 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Variables
        run: |
          echo image=${{ matrix.os }}-${{ matrix.variant }}:${{ matrix.version }} >> $GITHUB_ENV
          echo registry=${{ env.gh_registry }}/${{ github.repository_owner }} >> $GITHUB_ENV

      - name: Log in to registry
        run: podman login --username ${{ github.actor }} --password ${{ github.token }} ${registry}

      - name: Build container
        run: |
          podman build --build-arg FEDORA_VERSION=${{ matrix.version }} --build-arg VARIANT=${{ matrix.variant }} --tag ${image} --file Containerfile.${{ matrix.variant }}

      - name: Push container
        run: |
          podman push ${image} ${registry}/${image}

      - name: Log out of registry
        run: podman logout ${registry}
