name: build-os

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - '**.txt'
  schedule:
    - cron: '0 4 * * *'  # 04h00 UTC (after https://quay.io/repository/fedora-ostree-desktops/silverblue)
    # - cron: '30 8 * * *'  # 08h30 UTC (+0.5h after ublue-os main and nvidia)
  workflow_dispatch:  # allows you to run this workflow manually from the actions tab

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  registry: ghcr.io

permissions:
  contents: read
  packages: write

jobs:

  build-os:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ fedora ]
        variant: [ desktop, laptop ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to registry
        run: podman login --username ${{ github.actor }} --password ${{ github.token }} ${{ env.registry }}/${{ github.repository_owner }}

      - name: Build container
        run: |
          podman build --build-arg VARIANT=${{ matrix.variant }} --tag os:${{ matrix.variant }} --file Containerfile.${{ matrix.variant }}

      - name: Push container
        run: |
          podman push os:${{ matrix.variant }} ${{ env.registry }}/${{ github.repository_owner }}/${{ matrix.os }}:${{ matrix.variant }}

      - name: Log out of registry
        run: podman logout ${{ env.registry }}/${{ github.repository_owner }}
