name: build-os

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - '**.txt'
  schedule:
    - cron: '0 4 * * *'  # 04h00 UTC (after https://quay.io/repository/fedora-ostree-desktops/silverblue)
    # - cron: '30 8 * * *'  # 08h30 UTC (+0.5h after ublue-os main and nvidia)
  workflow_dispatch:  # allows you to run this workflow manually from the actions tab

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  registry: ghcr.io

permissions:
  contents: read
  packages: write

jobs:

  build-kmods:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version: [ 38, 39 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/${{ github.repository_owner }}

      - name: Generate variables
        id: variables
        run: |
          echo "datestamp=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "source-image=ghcr.io/fossrob/kmod-build:${{ matrix.version }}" >> $GITHUB_OUTPUT

      - name: Build image
        id: image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            Containerfile.build
          image: kmods
          tags: ${{ matrix.version }} ${{ matrix.version }}-${{ steps.variables.outputs.datestamp }}
          build-args: |
            SOURCE_IMAGE=${{ steps.variables.outputs.source-image }}
          oci: false
          layers: true
          extra-args: |
            --log-level error

      - name: Push to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          image: ${{ steps.image.outputs.image }}
          tags: ${{ steps.image.outputs.tags }}
          extra-args: |
            --disable-content-trust
  build-os:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ fedora ]
        variant: [ desktop, laptop ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to registry
        run: podman login --username ${{ github.actor }} --password ${{ github.token }} ${{ env.registry }}/${{ github.repository_owner }}

      - name: Build container
        run: |
          podman build --build-arg VARIANT=${{ matrix.variant }} --tag os:${{ matrix.variant }} --file Containerfile.${{ matrix.variant }}

      - name: Push container
        run: |
          podman push os:${{ matrix.variant }} ${{ env.registry }}/${{ github.repository_owner }}/${{ matrix.os }}:${{ matrix.variant }}

      - name: Log out of registry
        run: podman logout ${{ env.registry }}/${{ github.repository_owner }}
