name: build-os

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.txt'
  schedule:
    - cron: '09 00 * * *'  # 09h00 UTC (+1h after ublue-os main and nvidia)
  workflow_dispatch:  # allows you to run this workflow manually from the actions tab

env:
    IMAGE_NAME: os
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        base: [os, os-dx]
        flavor: [main, nvidia]
        version: [37, 38]
        exclude:
          - base: os
            flavor: nvidia
          - base: os
            flavor: main
            version: 37

    steps:
      - uses: actions/checkout@v3

      - name: Matrix Variables
        id: matrix-variables
        run: |
          if [[ "${{ matrix.flavor }}" == "main" ]]; then
              echo "IMAGE_NAME=${{ matrix.base }}" >> $GITHUB_ENV
          else
              echo "IMAGE_NAME=${{ format('{0}-{1}', matrix.base, matrix.flavor) }}" >> $GITHUB_ENV
          fi

      - name: Generate Tags
        id: generate-tags
        run: |
          BUILD_TAGS=()
          TIMESTAMP="$(date +%Y%m%d)"

          BUILD_TAGS=("${{ matrix.version }}" "${{ matrix.version }}-${TIMESTAMP}")

          echo "Generated the following build tags: "
          for TAG in "${BUILD_TAGS[@]}"; do
            echo "${TAG}"
          done

          alias_tags=("${BUILD_TAGS[@]}")
          echo "alias_tags=${alias_tags[*]}" >> $GITHUB_OUTPUT

      - name: Image Build
        id: image-build
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.generate-tags.outputs.alias_tags }}
          build-args: |
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            IMAGE_FLAVOR=${{ matrix.flavor }}
            FEDORA_MAJOR_VERSION=${{ matrix.version }}
          oci: false
          extra-args: |
            --target=${{ matrix.base }}

      - name: Push To Registry
        id: registry-push
        uses: redhat-actions/push-to-registry@v2
        env:
          REGISTRY_URL: ghcr.io/${{ github.repository_owner }}
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          # Name of the image/manifest to push (e.g. username/imagename or imagename)
          image: ${{ steps.image-build.outputs.image }}
          # 'The tag or tags of the image/manifest to push. For multiple tags, seperate by whitespace. For example, "latest v1"'
          tags: ${{ steps.image-build.outputs.tags }}
          # Hostname and optional namespace to push the image to (eg. quay.io/username or quay.io)
          registry: ${{ env.REGISTRY_URL }}
          # Username to use as credential to authenticate to the registry
          username: ${{ env.REGISTRY_USER }}
          # Password to use as credential to authenticate to the registry
          password: ${{ env.REGISTRY_PASSWORD }}
          # Extra args to be passed to podman push. Separate arguments by newline. Do not use quotes - @actions/exec will do the quoting for you.
          extra-args: |
            --disable-content-trust
