name: build-os

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.txt'
  schedule:
    - cron: '09 00 * * *'  # 09h00 UTC (+1h after ublue-os main and nvidia)
  workflow_dispatch:  # allows you to run this workflow manually from the actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        base: [os, os-dx]
        flavor: [main, nvidia]
        version: [38]
        exclude:
          - base: os
            flavor: nvidia

    env:
      IMAGE_NAME: os

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/${{ github.repository_owner }}

      - name: Matrix Variables
        run: |
          if [[ "${{ matrix.flavor }}" == "main" ]]; then
              echo "IMAGE_NAME=${{ matrix.base }}" >> $GITHUB_ENV
          else
              echo "IMAGE_NAME=${{ format('{0}-{1}', matrix.base, matrix.flavor) }}" >> $GITHUB_ENV
          fi

      - name: Generate Datestamp
        id: datestamp-generate
        run: |
          echo "datestamp=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Build Image
        id: image-build
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ matrix.version }} ${{ matrix.version }}-${{ steps.datestamp-generate.outputs.datestamp }}
          build-args: |
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            IMAGE_FLAVOR=${{ matrix.flavor }}
            FEDORA_MAJOR_VERSION=${{ matrix.version }}
          oci: false
          extra-args: |
            --target=${{ matrix.base }}

      - name: Push To Registry
        id: registry-push
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          image: ${{ steps.image-build.outputs.image }}
          tags: ${{ steps.image-build.outputs.tags }}
          extra-args: |
            --disable-content-trust
